### ISSUE TITLE
我可以改的，没想到吧

### ISSUE THREAD

**Issue by dongshunyao** [RinChanNOWWW/JobshopHomework#1]
我可以改的
 ---by author
我也可以改的，没想到吧（笑
何哲宇实在是太强辣OrzOrz膜膜膜

**Comment by JmPotato** [comment]
膜

**Comment by dongshunyao** [comment]
![1](https://user-images.githubusercontent.com/11513730/40228970-5dfc902e-5ac5-11e8-8f07-562e324de887.png)
看到了，看到了（手动滑稽）
